<?php

namespace IncentiveBundle\Repository;

use IncentiveBundle\Entity\Action;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param int $source
     * @return Action
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findBySource(int $source)
    {
        return $this->findOneBy(['id' => $source]);
    }
}
