<?php

namespace IncentiveBundle\Repository;

use IncentiveBundle\Entity\Action;
use IncentiveBundle\Entity\Booster;

/**
 * BoosterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoosterRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param int $source
     * @return Booster
     */
    public function findBySource(int $source): Booster
    {
        return $this->findOneBy(['id' => $source]);
    }

    /**
     * @param Action $source
     * @return Booster
     */
    public function findByAction(Action $action): ?Booster
    {
        return $this->findOneBy(['action' => $action]);
    }
}
